/** Declaration file generated by dts-gen */

export function MissingEnvVarsError(allowEmptyValues: any, dotenvFilename: any, exampleFilename: any, missingVars: any, error: any): void;

export function config(options: any): any;

export function load(options: any): any;

export function parse(src: any, options: any): any;

export namespace MissingEnvVarsError {
    namespace prototype {
        const message: string;

        const name: string;

        function toString(): any;

    }

}

export namespace config {
    const prototype: {
    };

}

export namespace load {
    const prototype: {
    };

}

export namespace parse {
    const prototype: {
    };

}
